//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid UserID { get; set; }
        public System.Guid JobID { get; set; }
        public string ApplicationStatus { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
