//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Jobby.Models.Extended;

    [MetadataType(typeof(EmployeeMetadata))]
    public partial class Employee
    {
        public System.Guid UserID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Salary { get; set; }
        public string JobStatus { get; set; }
        public string MilitaryStatus { get; set; }
        public string MartialStatus { get; set; }
        public string CareerLevel { get; set; }
        public byte[] CV { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
