//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Jobby.Models.Extended;

    [MetadataType(typeof(JobMetadata))]
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Applications = new HashSet<Application>();
            this.SavedJobs = new HashSet<SavedJob>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string Title { get; set; }
        public string JobDesc { get; set; }
        public System.DateTime PostDate { get; set; }
        public int CountryID { get; set; }
        public string City { get; set; }
        public int Salary { get; set; }
        public string JobStatus { get; set; }
        public string CareerLevel { get; set; }
        public int JobFieldID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Country Country { get; set; }
        public virtual JobField JobField { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedJob> SavedJobs { get; set; }
    }
}
