//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Jobby.Models.Extended;

    [MetadataType(typeof(UserEducationMetadata))]
    public partial class UserEducation
    {
        public System.Guid UserID { get; set; }
        public string Degree { get; set; }
        public string Entity { get; set; }
        public string Field { get; set; }
        public string Grade { get; set; }
        public string StartYear { get; set; }
        public string EndYear { get; set; }
    
        public virtual User User { get; set; }
    }
}
