//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Jobby.Models.Extended;

    [MetadataType(typeof(UserSkillMetadata))]
    public partial class UserSkill
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string SkillName { get; set; }
        public byte SkillLevel { get; set; }
        public bool IsLanguage { get; set; }
    
        public virtual User User { get; set; }
    }
}
